name: Metrics
on:
  # Schedule updates (every 12 hours)
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LuffyWesley
          template: classic
          base: ""
          config_timezone: America/Los_Angeles
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, jupyter notebook # List of languages to ignore
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage # Additionally display total bytes size and percentage
          plugin_languages_threshold: 0%
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"
